import type { NextPage } from 'next';
import Head from 'next/head';

import BaseLayout from '../layouts/BaseLayout';

const Blog: NextPage = function () {
	return (
		<BaseLayout>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			blog
		</BaseLayout>
	);
};

export default Blog;
