import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Teste = styled.h1`
  color: red;
  text-decoration: underline;
  font-size: 80px;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Teste>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Teste>
        <h1>Yellow</h1>
      </main>
    </div>
  );
};

export default Home;
