import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';

import { Title } from '../components/Title';

const Wrapper = styled.main`
	display: flex;
	justify-content: center;
	align-items: center;
	min-height: 100vh;
`;

const Home: NextPage = function () {
	return (
		<div>
			<Head>
				<title>Igor Faustino</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Wrapper>
				<div>
					<Title>IGOR N FAUSTINO</Title>
					<p>
						Hi, I'am Igor and currently I'am working as a Web Developer at
						aftersale
					</p>
				</div>
			</Wrapper>
		</div>
	);
};

export default Home;
